apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/jsonserver

images:
  - name: controller:latest
    newName: ttl.sh/jsonserver-operator-d49e3c91248e670b741cd01e09808cd16941cb6a
    newTag: 30m


flux-gitops