apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/jsonserver

images:
  - name: controller:latest
    newName: ttl.sh/jsonserver-operator-af4627cae78c671d91e913d3bd5999052cf17b4a
    newTag: 30m