apiVersion: server.vambita.com/v1alpha1
kind: JsonServer
metadata:
  labels:
    app.kubernetes.io/name: json-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-instance01
spec:
  replicas: 1
  jsonConfig: |
    {
      "people": [
        {
          "id": 1,
          "name": "Harold Finch"
        },
        {
          "id": 2,
          "name": "John Reese"
        },
        {
          "id": 3,
          "name": "Joss Carter"
        }
      ]
    }